### ISSUE TITLE
Error message/required attributes not working

### ISSUE THREAD

**Issue by geoffhuntsgood** [NeilujD/paper-autocomplete-input#1]
Hello! I love this component, it's been really useful converting to it from old Bootstrap typeaheads. However, it seems like some of the paper behaviors aren't working - for example, in the demo, when entering focus on the component and then exiting without typing anything, nothing happens even though "required" is defined.

Expected outcome:  Element turns red and displays error message when leaving focus and selectedItem is empty or follows an incorrect pattern.

Actual outcome:  Nothing happens.

Code:  This happens in the demo.

**Comment by NeilujD** [comment]
Hi @ghuntoon !
I am glad you like it !
Can you give me an example of an actual element working that way ?
I am not sure it is the purpose of the `required` attribute, it is more about the form validation at the submit.
If you want something that dynamic I would suggest you to update the `invalid` attribute to true to display your `error-message` on the `item-selected` event if no item is selected.
The best way would be to add the `validate` method to make it with more laziness and that is for sure something I will implement in the next release.

**Comment by geoffhuntsgood** [comment]
I am so sorry that I did not respond! This is the perfect way to deal with this situation.
