### ISSUE TITLE
Firebase support

### ISSUE THREAD

**Issue by phidias51** [NeilujD/paper-autocomplete-input#2]
I was wondering if you had thought of refactoring the component so that the loading data can be accomplished via different strategies? For example, you might have a RESTLoader, and a FirebaseLoader. These loaders could be implemented as different behaviors, or as different ES6 classes.

**Comment by NeilujD** [comment]
Hi @phidias51 !
For now you can directly set a list of items instead of giving an url so it could be a workaround until this kind a feature is added.
Still you will notice that there is an issue about this workaround and I will work on it as soon as possible on it to fix it.
