### ISSUE TITLE
Default value for input?

### ISSUE THREAD

**Issue by geoffhuntsgood** [NeilujD/paper-autocomplete-input#4]
Thank you for indulging me over the past few days!

Is there an appropriate way to set a default value for a paper-autocomplete-input? If I set the value manually on page load, the value shows in the field but does not remain after focusing in and then focusing out. I know that the initial value I'm setting will be one of the options presented in the dropdown list. Here's an example:

`<paper-autocomplete-input autoc-url="url" autoc-fields='["field"]' value="value">`
`</paper-autocomplete-input>`

Expected Outcome:

The manually-set value appears in the input on page load. Clicking on the input and then clicking away (or tabbing through the input) does not change the value.

Actual Outcome:

The manually-set value appears in the input on page load, but clicking on the input and then clicking away (or tabbing through) makes the manually-set value disappear.

Thanks again!

**Comment by NeilujD** [comment]
Hi @ghuntoon !
Have you tried to bind to the `selectedItem` property instead of the `value` property ?
Of course you will have to bind it to an `Object` type variable.
It should behave the way you expect.

**Comment by geoffhuntsgood** [comment]
Wonderful! I had tried binding to selectedItem, but I was binding a String, not an Object. Thank you!
